@startuml
set separator none
title Models

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("NextSkillApplication.NextSkillApplication_boundary", "NextSkillApplication", $tags="") {
  Component(NextSkillApplication.NextSkillApplication.Models, "Models", $techn="Module", $descr="", $tags="", $link="")
  Component(NextSkillApplication.NextSkillApplication.Course, "Course", $techn="Module", $descr="", $tags="", $link="")
  Component(NextSkillApplication.NextSkillApplication.User, "User", $techn="Module", $descr="", $tags="", $link="")
}

Rel(NextSkillApplication.NextSkillApplication.User, NextSkillApplication.NextSkillApplication.Models, "depends on", $techn="", $tags="", $link="")
Rel(NextSkillApplication.NextSkillApplication.Models, NextSkillApplication.NextSkillApplication.Course, "depends on", $techn="", $tags="", $link="")
Rel(NextSkillApplication.NextSkillApplication.Models, NextSkillApplication.NextSkillApplication.User, "depends on", $techn="", $tags="", $link="")
Rel(NextSkillApplication.NextSkillApplication.Course, NextSkillApplication.NextSkillApplication.Models, "depends on", $techn="", $tags="", $link="")
Rel(NextSkillApplication.NextSkillApplication.Course, NextSkillApplication.NextSkillApplication.User, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml